development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: farm_hand_dev
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: farm_hand_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

