development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: farm_hand_development
  pool: 5
  username: hemashree
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: farm_hand_test
  pool: 5
  username: hemashree
  password: 
  host: localhost
  port: 5432

